[build]
  command = "cd todolist && npm install && npm run build"
  publish = "todolist/build"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "todolist/build/*, todolist/public/config.js"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200